#!/bin/bash
# creates blurred screenshot of current desktop and uses it as image for i3lock
# new: use ffmpeg for blurring (much faster than convert!)

# make screenshot of current desktop, put the lock image on top and invoke i3lock

import -window root ~/lockscreen.png && \
ffmpeg -y -v 0 -hide_banner -i ~/lockscreen.png -filter:v boxblur=5:5 ~/lockscreen.png && \
composite .config/i3/lock_circle.png -geometry +690+270 ~/lockscreen.png ~/lockscreen.png && \
i3lock -i ~/lockscreen.png && \
rm ~/lockscreen.png

